on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test -v
      - name: Local test
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "John Doe"
          ./t/01-furo5
